### ISSUE TITLE
Feature 1 : User can view the product catalog 

### ISSUE THREAD

**Issue by hannahhoanggg** [hannahhoanggg/Thermal-Hydrate#1]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can view the products catalog on the products page. 

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

After viewing the home page, user can click on the products page and browse through the catalog. 

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![Screenshot 2023-09-29 150703](https://github.com/hannahhoanggg/Thermal-Hydrate/assets/136301731/5dae2bc1-90f3-404e-859a-b14d77e61526)
![Screenshot 2023-09-29 150713](https://github.com/hannahhoanggg/Thermal-Hydrate/assets/136301731/6fbc4ad7-bfa0-4890-8844-424fc8d8d6f7)

## ✅ Task Lists

> ##### Commit checklists for tasks needed to complete the feature.

### 🐘 Database Tasks

- [x] Update `schema.sql` to have the exported version of the database schema tables.
- [x] Update `data.sql` to have the database values that are needed for the products catalog.

### ☁️ Server Tasks

- [x] Update `server.js` to create paths to receive the CRUD operations that are needed
- [x] Test with HTTPie
- [x] Handle all errors and respond to the client

### ⚡ Client Tasks

- [x] Create a component for the navigation bar that can functionally view the home page.
- [x] Create React components for the  navigation bar that can functionally view the products page once clicked.

### 🧑‍⚕️ Clean Up Tasks
- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
