### ISSUE TITLE
Feature 3: User can create an account 

### ISSUE THREAD

**Issue by hannahhoanggg** [hannahhoanggg/Thermal-Hydrate#3]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can create an account through the app. 

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

User will be able to create an account to have the option to log in or out. 

## ✅ Task Lists

> ##### Commit checklists for tasks needed to complete the feature.

### ☁️ Server Tasks

- [x] Test with HTTPie that you are able to create an account & retrieve user's information.
- [x] Handle all errors and respond to the client

### ⚡ Client Tasks

- [x] Create a component for the user to be able to register an account through the registration form.
- [x] Create a component for the user to be able to sign in with the sign-in form.

### 🧑‍⚕️ Clean Up Tasks

- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [ ] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [ ] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [ ] Remove all console logs.
- [ ] Remove all commented out code.
- [ ] Remove all CSS properties that have no effect.
- [ ] Check all code for proper formatting and indentation.
- [ ] Confirm that there are no errors in the console while using the application.
- [ ] Confirm that all previous functionality still works without errors.
- [ ] Confirm that the user interface looks natural on both mobile and desktop screens.
- [ ] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
