### ISSUE TITLE
Feature 4: User can add a product to their shopping cart

### ISSUE THREAD

**Issue by hannahhoanggg** [hannahhoanggg/Thermal-Hydrate#4]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can add a product to their shopping cart. 

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

After viewing a product, the user will be able to add an item to their shopping cart. 

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.
![Screenshot 2023-10-01 202414](https://github.com/hannahhoanggg/Thermal-Hydrate/assets/136301731/7c05bdff-ebb6-4f60-bcf2-1f5dab09f5ac)

## ✅ Task Lists

> ##### Commit checklists for tasks needed to complete the feature.

### ☁️ Server Tasks
- [x] Test with HTTPie
- [x] Handle all errors and respond to the client

### ⚡ Client Tasks

- [x] Create a component to allow the user to view the shopping cart page with the products that were added to the cart.
- [x] Update component in the products details page to allow user to functionally use add to cart button. 

### 🧑‍⚕️ Clean Up Tasks
- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
