### ISSUE TITLE
Feature 5: User can update their shopping cart 

### ISSUE THREAD

**Issue by hannahhoanggg** [hannahhoanggg/Thermal-Hydrate#5]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can update their shopping cart. 

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

If the user changes their mind about a product, the user will be able to remove a product from the shopping cart by clicking on the trash can button. 

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![Screenshot 2023-10-01 202414](https://github.com/hannahhoanggg/Thermal-Hydrate/assets/136301731/b88350c5-5a6c-426b-b2ad-3f4fcd8979d2)

## ✅ Task Lists

> ##### Commit checklists for tasks needed to complete the feature.

### ☁️ Server Tasks

- [x] Update `server.js` to be able to update the quantity.

### ⚡ Client Tasks

- [x] Create a component to update the quantity of items in the cart. 

### 🧑‍⚕️ Clean Up Tasks

- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
