### ISSUE TITLE
Feature 6: User can remove a product from their shopping cart 

### ISSUE THREAD

**Issue by hannahhoanggg** [hannahhoanggg/Thermal-Hydrate#6]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can remove a product from their shopping cart.

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

The user can update their shopping cart by changing the quantity of products. 

## ✅ Task Lists

> ##### Commit checklists for tasks needed to complete the feature.

### ⚡ Client Tasks

- [x] Update the cart component to be able to delete item from the cart. 
- [x] Make sure that once the cart is empty, the page will show message without the order summary page. 

### 🧑‍⚕️ Clean Up Tasks
- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
