### ISSUE TITLE
Feature 7: User can checkout from the shopping cart 

### ISSUE THREAD

**Issue by hannahhoanggg** [hannahhoanggg/Thermal-Hydrate#7]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can checkout from the shopping cart.

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

After adding a product to the shopping cart, the user can complete the purchase by checking out from the shopping cart.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![Screenshot 2023-10-01 202414](https://github.com/hannahhoanggg/Thermal-Hydrate/assets/136301731/f363fd53-feee-46ce-8343-938cc1d727c5)

## ✅ Task Lists

> ##### Commit checklists for tasks needed to complete the feature.

### 🧑‍⚕️ Clean Up Tasks
- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
